spring:
    datasource:
        name: ims
        url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/ims?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: ims
        password: 042d4b51fb8c33e42266
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    data:
        mongodb:
            uri: mongodb://imserver:042d4b51fb8c33e42266@xxx.xxx.xxx.xxx:27017/imserver
    redis:
      host: xxx.xxx.xxx.xxx
      port: 6379
      password: 042d4b51fb8c33e42266
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          min-idle: 0
          max-idle: 8

    cache:
      type: redis
    application:
      name: imserver-user
#    cloud:
#      zookeeper:
#        discovery:
#          root: /im-service
#          register: true
#          enabled: true
#        connect-string: xxx.xxx.xxx.xxx:2181

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ququ.imserver.user.pojo
    configuration:
      cache-enabled: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



server:
  compression:
    enabled: true
  port: 8073
  session:
    timeout: 60


logging:
  level:
    com.ququ.imserver.user: debug
  config: classpath:logback.xml

feign:
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 60000
