spring:
    data:
        mongodb:
            uri: mongodb://imserver:042d4b51fb8c33e42266@xxx.xxx.xxx.xxx:27017/imserver



server:
  compression:
    enabled: true
  port: 8071
  session:
    timeout: 60


logging:
  level:
    com.ququ.imserver.api.rongcloud: debug
  config: classpath:logback.xml

